name: Update M3U

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:      # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 当前仓库
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 下载并处理 m3u
        run: |
          pip install requests
          python process_m3u.py

      - name: 提交更新
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add GuangdongIPTV_http.m3u
          git commit -m "自动更新 M3U 文件" || echo "No changes to commit"
          git push
